### ISSUE TITLE
不可变 let?

### ISSUE THREAD

**Issue by xen0n** [qiniu/bpl#1]
spec 里 `let x = y` 总能成功，不够函数式，可能导致写出 bug 而不自知。

参考一些其他语言，加入一旦赋值就不可改变的 `let` 绑定如何？没有看具体实现，也许实现上做进 qlang 会更好。

**Comment by xushiwei** [comment]
bpl 的目标是做一个小巧的语言，所以不会太考虑复杂工程会面临的问题。

**Comment by xen0n** [comment]
哦，原来没有打算跟 protobuf、wuffs 这些竞争同一块需求。。
