### ISSUE TITLE
wuffs?

### ISSUE THREAD

**Issue by xen0n** [qiniu/bpl#2]
Google 前一阵子也搞了[一个相当类似的东西](https://github.com/google/wuffs)，也是 Go 实现的，这个项目除了集成 qlang 之外还有什么优势？（比如学习曲线之类？）

**Comment by xushiwei** [comment]
看起来目的非常不一样。对比一下 gif 格式的支持：
* https://github.com/google/wuffs/blob/master/std/gif/decode_gif.wuffs
* https://github.com/qiniu/bpl/blob/master/formats/gif.bpl
